apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap-deploy
  namespace: vsanchez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      imagePullSecrets:
        - name: ibm-registry-secret
      containers:
        - name: zap
          image: "icr.io/cr-vsanchez/zap2docker-stable"
          ports:
            - containerPort: 8099
          args:
            - zap.sh
            - -daemon
            - -host
            - 0.0.0.0
            - -port
            - "8099"
            - -config
            - api.addrs.addr.name=.*
            - -config
            - api.addrs.addr.regex=true
            - -config
            - api.disablekey=true
            - -config
            - server.ssl.key=/etc/ssl/certs/zap.key
            - -config
            - server.ssl.cert=/etc/ssl/certs/zap.crt
          volumeMounts:
            - name: zap-data
              mountPath: /home/zap/.ZAP/
            - name: zap-tls-secret
              mountPath: /etc/ssl/certs/
              readOnly: true
      volumes:
        - name: zap-data
          emptyDir: {}
        - name: zap-tls-secret
          secret:
            secretName: zap-tls-secret
