apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: zap-route
  namespace: vsanchez
spec:
  to:
    kind: Service
    name: zap-service
  port:
    targetPort: 8099
  tls:
    termination: passthrough
  wildcardPolicy: None