name: Prueba de ZAP
on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'URL a probar'
        required: true
permissions:
  issues: write
jobs:
  zap:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Run ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: '${{ github.event.inputs.url }}'
        token: ${{ secrets.TOKEN }}
        artifact_name: Escaneo_ZAP-${{ github.event.inputs.url }}-${{ env.DATE }}
