name: Prueba de ZAP
on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'URL a probar'
        required: true

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
    - name: Run ZAP
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'route-develop-vsanchez.ez-ibm-openshift-vpc-lkmc-b9be9ed6ae33d743815245d0b773ebc7-0000.eu-es.containers.appdomain.cloud'
        rules_file_name: '.zap/rules.tsv'