name: Prueba de ZAP

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL a probar'
        required: true

permissions:
  issues: write

jobs:
  zap:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar variables
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
          SCAN_URL: ${{ github.event.inputs.url }}
        run: |
          echo "Configurando variables..."
          if [ -z "$ZAP_API_KEY" ]; then
            echo "ERROR: ZAP_API_KEY no está configurado."
            exit 1
          fi
          echo "URL configurada para el escaneo: $SCAN_URL"

      - name: Ejecutar ZAP Spider
        env:
          ZAP_API_URL: "http://localhost:8080"
          SCAN_URL: ${{ github.event.inputs.url }}
        run: |
          echo "Iniciando el Spider de ZAP..."
          curl "${ZAP_API_URL}/JSON/spider/action/scan/?url=${SCAN_URL}" -o zap_spider_start.json
          cat zap_spider_start.json

      - name: Monitorizar estado del Spider
        env:
          ZAP_API_URL: "http://localhost:8080"
        run: |
          echo "Comprobando estado del Spider..."
          until [ "$(curl -s "${ZAP_API_URL}/JSON/spider/view/status/" | grep -o '100')" ]; do
            echo 'El Spider está en ejecución...'; sleep 5;
          done
          echo "El Spider ha finalizado."

      - name: Generar informe HTML
        env:
          ZAP_API_URL: "http://localhost:8080"
        run: |
          echo "Generando informe en HTML..."
          curl "${ZAP_API_URL}/OTHER/core/other/htmlreport/" -o "zap_report_$(date +'%Y%m%d_%H%M%S').html"

      - name: Subir informe de ZAP
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report_*.html
