name: Prueba de ZAP
on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'URL a probar'
        required: true
permissions:
  issues: write
jobs:
  zap:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: '${{ github.event.inputs.url }}'
        token: ${{ secrets.TOKEN }}
        artifact_name: zap_scan

    - name: Copy Reports to Runner
      run: |
        cp /home/user/actions-runner/_work/prueba/prueba/report_html.html .
        cp /home/user/actions-runner/_work/prueba/prueba/report_md.md .
        cp /home/user/actions-runner/_work/prueba/prueba/report_json.json .

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: |
          report_html.html
          report_md.md
          report_json.json
