name: Prueba de ZAP
on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'URL a probar'
        required: true
permissions:
  issues: write
jobs:
  zap:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: '${{ github.event.inputs.url }}'
        token: ${{ secrets.TOKEN }}
        fail_on_warn: false 
        format: html        
        report: 'zap-report.html' 

    - name: cat zap-report.html
      run: cat zap-report.html
