name: Prueba de ZAP
on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'URL a probar'
        required: true
permissions:
  issues: write
jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
    - name: Run ZAP
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: '${{ github.event.inputs.url }}'
        